#!/usr/bin/env bash

# find nvidia gpus
if [[ -d /proc/driver/nvidia/gpus ]]
then
    for gpu in /proc/driver/nvidia/gpus/*/numa_status
    do
        node=$(head -n 1 "${gpu}" | awk '{ print $2 }')
        echo "${node} NVIDIA GPU"
    done
fi
