#!/bin/bash

mkdir tmp_build_dir
mkdir tmp_build_dir/header_temp_dir

/home/zingale/development/AMReX//Tools/F_scripts/write_cuda_headers.py \
             --output_dir tmp_build_dir/header_temp_dir \
             --vpath "/home/zingale/development/Microphysics/util /home/zingale/development/AMReX//Src/Base /home/zingale/development/AMReX//Src/AmrCore /home/zingale/development/AMReX//Src/Amr /home/zingale/development/AMReX//Src/Boundary  /home/zingale/development/Microphysics/EOS/helmholtz  /home/zingale/development/Microphysics/networks/aprox13  /home/zingale/development/Microphysics/EOS  /home/zingale/development/Microphysics/networks  ..//Source /home/zingale/development/AMReX//Src/F_BaseLib" \
             --headers "Castro_F.H" \
             --fortran "actual_eos.F90 actual_network.F90 microphysics_math.F90 AMReX_COORDSYS_3D.F90 AMReX_FILCC_3D.F90 AMReX_BLutil_F.F90 AMReX_BLBoxLib_F.F90 AMReX_BLProfiler_F.F90 AMReX_BaseFab_nd.F90 AMReX_MultiFabUtil_nd.F90 AMReX_filcc_mod.F90 AMReX_omp_mod.F90 AMReX_fort_mod.F90 AMReX_error_mod.F90 AMReX_parmparse_mod.F90 AMReX_string_mod.F90 AMReX_bc_types_mod.F90 AMReX_io_mod.F90 AMReX_ParallelDescriptor_F.F90 AMReX_CUDA.F90 AMReX_FLUXREG_3D.F90 AMReX_FLUXREG_nd.F90 AMReX_INTERP_3D.F90 AMReX_FillPatchUtil_3d.F90 AMReX_INTERPBNDRYDATA_3D.F90 AMReX_LO_UTIL.F90 AMReX_YAFluxRegister_3d.F90 AMReX_YAFluxRegister_nd.F90 AMReX_lo_bctypes_mod.F90 ppm.F90 Castro_mol.F90  riemann.F90  bc_fill.F90 Prob.F90 probdata.F90 Castro_util.F90 advection_util.F90 Tagging.F90 meth_params.F90 prob_params.F90 timestep.F90 flatten.F90 io.F90 castro_c_interfaces.F90 eos.F90 eos_type.F90 network.F90 extern.F90 constants_cgs.F90 " \
             --cpp "gcc -E -P" \
             --defines "-DNDEBUG -DAMREX_GIT_VERSION=\"18.06-714-g81a89ccd4baf-dirty\" -DBL_GCC_VERSION=7.3.1 -DBL_GCC_MAJOR_VERSION=7 -DBL_GCC_MINOR_VERSION=3 -DCUDA -DAMREX_USE_CUDA -DAMREX_USE_DEVICE -DCUDA_UM -DAMREX_USE_CUDA_UM -DBL_COALESCE_FABS -DAMREX_LAUNCH='attributes(global)' -DAMREX_DEVICE='attributes(device)' -DBL_SPACEDIM=3 -DAMREX_SPACEDIM=3 -DBL_FORT_USE_UNDERSCORE -DAMREX_FORT_USE_UNDERSCORE -DBL_Linux -DAMREX_Linux -DCUDA_MAX_THREADS=256 -DCRSEGRNDOMP -DBL_USE_F_BASELIB -I. -I/usr/local/cuda-9.2/include -Itmp_build_dir/header_temp_dir -I/home/zingale/development/Microphysics/util -I/home/zingale/development/AMReX//Src/Base -I/home/zingale/development/AMReX//Src/AmrCore -I/home/zingale/development/AMReX//Src/Amr -I/home/zingale/development/AMReX//Src/Boundary -I/home/zingale/development/Microphysics/EOS/helmholtz -I/home/zingale/development/Microphysics/networks/aprox13 -I/home/zingale/development/Microphysics/EOS -I/home/zingale/development/Microphysics/networks -I..//Source -I/home/zingale/development/AMReX//Src/F_BaseLib -I/home/zingale/development/AMReX//Tools/C_scripts"
